/* eslint-disable jsdoc/require-jsdoc, @typescript-eslint/consistent-type-definitions */
export type Styles = {
    'are-large': string
    'are-medium': string
    'are-small': string
    block: string
    box: string
    breadcrumb: string
    button: string
    buttons: string
    card: string
    'card-content': string
    'card-footer': string
    'card-footer-item': string
    'card-header': string
    'card-header-icon': string
    'card-header-title': string
    'card-image': string
    checkbox: string
    column: string
    columns: string
    container: string
    content: string
    control: string
    delete: string
    dropdown: string
    'dropdown-content': string
    'dropdown-divider': string
    'dropdown-item': string
    'dropdown-menu': string
    fa: string
    field: string
    'field-body': string
    'field-label': string
    file: string
    'file-cta': string
    'file-icon': string
    'file-input': string
    'file-label': string
    'file-name': string
    footer: string
    'has-addons': string
    'has-addons-centered': string
    'has-addons-fullwidth': string
    'has-addons-right': string
    'has-arrow-separator': string
    'has-background-black': string
    'has-background-black-bis': string
    'has-background-black-ter': string
    'has-background-danger': string
    'has-background-danger-dark': string
    'has-background-danger-light': string
    'has-background-dark': string
    'has-background-grey': string
    'has-background-grey-dark': string
    'has-background-grey-darker': string
    'has-background-grey-light': string
    'has-background-grey-lighter': string
    'has-background-info': string
    'has-background-info-dark': string
    'has-background-info-light': string
    'has-background-light': string
    'has-background-link': string
    'has-background-link-dark': string
    'has-background-link-light': string
    'has-background-primary': string
    'has-background-primary-dark': string
    'has-background-primary-light': string
    'has-background-success': string
    'has-background-success-dark': string
    'has-background-success-light': string
    'has-background-warning': string
    'has-background-warning-dark': string
    'has-background-warning-light': string
    'has-background-white': string
    'has-background-white-bis': string
    'has-background-white-ter': string
    'has-bullet-separator': string
    'has-dot-separator': string
    'has-dropdown': string
    'has-dropdown-up': string
    'has-fixed-size': string
    'has-icons-left': string
    'has-icons-right': string
    'has-name': string
    'has-navbar-fixed-bottom': string
    'has-navbar-fixed-bottom-desktop': string
    'has-navbar-fixed-bottom-touch': string
    'has-navbar-fixed-top': string
    'has-navbar-fixed-top-desktop': string
    'has-navbar-fixed-top-touch': string
    'has-ratio': string
    'has-shadow': string
    'has-spaced-navbar-fixed-bottom': string
    'has-spaced-navbar-fixed-top': string
    'has-succeeds-separator': string
    'has-text-black': string
    'has-text-black-bis': string
    'has-text-black-ter': string
    'has-text-centered': string
    'has-text-centered-desktop': string
    'has-text-centered-desktop-only': string
    'has-text-centered-fullhd': string
    'has-text-centered-mobile': string
    'has-text-centered-tablet': string
    'has-text-centered-tablet-only': string
    'has-text-centered-touch': string
    'has-text-centered-widescreen': string
    'has-text-centered-widescreen-only': string
    'has-text-danger': string
    'has-text-danger-dark': string
    'has-text-danger-light': string
    'has-text-dark': string
    'has-text-grey': string
    'has-text-grey-dark': string
    'has-text-grey-darker': string
    'has-text-grey-light': string
    'has-text-grey-lighter': string
    'has-text-info': string
    'has-text-info-dark': string
    'has-text-info-light': string
    'has-text-justified': string
    'has-text-justified-desktop': string
    'has-text-justified-desktop-only': string
    'has-text-justified-fullhd': string
    'has-text-justified-mobile': string
    'has-text-justified-tablet': string
    'has-text-justified-tablet-only': string
    'has-text-justified-touch': string
    'has-text-justified-widescreen': string
    'has-text-justified-widescreen-only': string
    'has-text-left': string
    'has-text-left-desktop': string
    'has-text-left-desktop-only': string
    'has-text-left-fullhd': string
    'has-text-left-mobile': string
    'has-text-left-tablet': string
    'has-text-left-tablet-only': string
    'has-text-left-touch': string
    'has-text-left-widescreen': string
    'has-text-left-widescreen-only': string
    'has-text-light': string
    'has-text-link': string
    'has-text-link-dark': string
    'has-text-link-light': string
    'has-text-primary': string
    'has-text-primary-dark': string
    'has-text-primary-light': string
    'has-text-right': string
    'has-text-right-desktop': string
    'has-text-right-desktop-only': string
    'has-text-right-fullhd': string
    'has-text-right-mobile': string
    'has-text-right-tablet': string
    'has-text-right-tablet-only': string
    'has-text-right-touch': string
    'has-text-right-widescreen': string
    'has-text-right-widescreen-only': string
    'has-text-success': string
    'has-text-success-dark': string
    'has-text-success-light': string
    'has-text-warning': string
    'has-text-warning-dark': string
    'has-text-warning-light': string
    'has-text-weight-bold': string
    'has-text-weight-light': string
    'has-text-weight-medium': string
    'has-text-weight-normal': string
    'has-text-weight-semibold': string
    'has-text-white': string
    'has-text-white-bis': string
    'has-text-white-ter': string
    heading: string
    help: string
    hero: string
    'hero-body': string
    'hero-buttons': string
    'hero-foot': string
    'hero-head': string
    'hero-video': string
    icon: string
    'icon-text': string
    image: string
    input: string
    'is-0': string
    'is-0-desktop': string
    'is-0-desktop-only': string
    'is-0-fullhd': string
    'is-0-mobile': string
    'is-0-tablet': string
    'is-0-tablet-only': string
    'is-0-touch': string
    'is-0-widescreen': string
    'is-0-widescreen-only': string
    'is-1': string
    'is-1-desktop': string
    'is-1-desktop-only': string
    'is-1-fullhd': string
    'is-1-mobile': string
    'is-1-tablet': string
    'is-1-tablet-only': string
    'is-1-touch': string
    'is-1-widescreen': string
    'is-1-widescreen-only': string
    'is-10': string
    'is-10-desktop': string
    'is-10-fullhd': string
    'is-10-mobile': string
    'is-10-tablet': string
    'is-10-touch': string
    'is-10-widescreen': string
    'is-11': string
    'is-11-desktop': string
    'is-11-fullhd': string
    'is-11-mobile': string
    'is-11-tablet': string
    'is-11-touch': string
    'is-11-widescreen': string
    'is-12': string
    'is-12-desktop': string
    'is-12-fullhd': string
    'is-12-mobile': string
    'is-12-tablet': string
    'is-12-touch': string
    'is-12-widescreen': string
    'is-128x128': string
    'is-16by9': string
    'is-16x16': string
    'is-1by1': string
    'is-1by2': string
    'is-1by3': string
    'is-2': string
    'is-2-desktop': string
    'is-2-desktop-only': string
    'is-2-fullhd': string
    'is-2-mobile': string
    'is-2-tablet': string
    'is-2-tablet-only': string
    'is-2-touch': string
    'is-2-widescreen': string
    'is-2-widescreen-only': string
    'is-24x24': string
    'is-2by1': string
    'is-2by3': string
    'is-3': string
    'is-3-desktop': string
    'is-3-desktop-only': string
    'is-3-fullhd': string
    'is-3-mobile': string
    'is-3-tablet': string
    'is-3-tablet-only': string
    'is-3-touch': string
    'is-3-widescreen': string
    'is-3-widescreen-only': string
    'is-32x32': string
    'is-3by1': string
    'is-3by2': string
    'is-3by4': string
    'is-3by5': string
    'is-4': string
    'is-4-desktop': string
    'is-4-desktop-only': string
    'is-4-fullhd': string
    'is-4-mobile': string
    'is-4-tablet': string
    'is-4-tablet-only': string
    'is-4-touch': string
    'is-4-widescreen': string
    'is-4-widescreen-only': string
    'is-48x48': string
    'is-4by3': string
    'is-4by5': string
    'is-5': string
    'is-5-desktop': string
    'is-5-desktop-only': string
    'is-5-fullhd': string
    'is-5-mobile': string
    'is-5-tablet': string
    'is-5-tablet-only': string
    'is-5-touch': string
    'is-5-widescreen': string
    'is-5-widescreen-only': string
    'is-5by3': string
    'is-5by4': string
    'is-6': string
    'is-6-desktop': string
    'is-6-desktop-only': string
    'is-6-fullhd': string
    'is-6-mobile': string
    'is-6-tablet': string
    'is-6-tablet-only': string
    'is-6-touch': string
    'is-6-widescreen': string
    'is-6-widescreen-only': string
    'is-64x64': string
    'is-7': string
    'is-7-desktop': string
    'is-7-desktop-only': string
    'is-7-fullhd': string
    'is-7-mobile': string
    'is-7-tablet': string
    'is-7-tablet-only': string
    'is-7-touch': string
    'is-7-widescreen': string
    'is-7-widescreen-only': string
    'is-8': string
    'is-8-desktop': string
    'is-8-desktop-only': string
    'is-8-fullhd': string
    'is-8-mobile': string
    'is-8-tablet': string
    'is-8-tablet-only': string
    'is-8-touch': string
    'is-8-widescreen': string
    'is-8-widescreen-only': string
    'is-9': string
    'is-9-desktop': string
    'is-9-fullhd': string
    'is-9-mobile': string
    'is-9-tablet': string
    'is-9-touch': string
    'is-9-widescreen': string
    'is-96x96': string
    'is-9by16': string
    'is-active': string
    'is-align-content-baseline': string
    'is-align-content-center': string
    'is-align-content-end': string
    'is-align-content-flex-end': string
    'is-align-content-flex-start': string
    'is-align-content-space-around': string
    'is-align-content-space-between': string
    'is-align-content-space-evenly': string
    'is-align-content-start': string
    'is-align-content-stretch': string
    'is-align-items-baseline': string
    'is-align-items-center': string
    'is-align-items-end': string
    'is-align-items-flex-end': string
    'is-align-items-flex-start': string
    'is-align-items-self-end': string
    'is-align-items-self-start': string
    'is-align-items-start': string
    'is-align-items-stretch': string
    'is-align-self-auto': string
    'is-align-self-baseline': string
    'is-align-self-center': string
    'is-align-self-flex-end': string
    'is-align-self-flex-start': string
    'is-align-self-stretch': string
    'is-ancestor': string
    'is-arrowless': string
    'is-black': string
    'is-block': string
    'is-block-desktop': string
    'is-block-desktop-only': string
    'is-block-fullhd': string
    'is-block-mobile': string
    'is-block-tablet': string
    'is-block-tablet-only': string
    'is-block-touch': string
    'is-block-widescreen': string
    'is-block-widescreen-only': string
    'is-bold': string
    'is-bordered': string
    'is-boxed': string
    'is-capitalized': string
    'is-center': string
    'is-centered': string
    'is-child': string
    'is-clearfix': string
    'is-clickable': string
    'is-clipped': string
    'is-current': string
    'is-danger': string
    'is-dark': string
    'is-delete': string
    'is-desktop': string
    'is-disabled': string
    'is-empty': string
    'is-expanded': string
    'is-family-code': string
    'is-family-monospace': string
    'is-family-primary': string
    'is-family-sans-serif': string
    'is-family-secondary': string
    'is-fixed-bottom': string
    'is-fixed-bottom-desktop': string
    'is-fixed-bottom-touch': string
    'is-fixed-top': string
    'is-fixed-top-desktop': string
    'is-fixed-top-touch': string
    'is-flex': string
    'is-flex-desktop': string
    'is-flex-desktop-only': string
    'is-flex-direction-column': string
    'is-flex-direction-column-reverse': string
    'is-flex-direction-row': string
    'is-flex-direction-row-reverse': string
    'is-flex-fullhd': string
    'is-flex-grow-0': string
    'is-flex-grow-1': string
    'is-flex-grow-2': string
    'is-flex-grow-3': string
    'is-flex-grow-4': string
    'is-flex-grow-5': string
    'is-flex-mobile': string
    'is-flex-shrink-0': string
    'is-flex-shrink-1': string
    'is-flex-shrink-2': string
    'is-flex-shrink-3': string
    'is-flex-shrink-4': string
    'is-flex-shrink-5': string
    'is-flex-tablet': string
    'is-flex-tablet-only': string
    'is-flex-touch': string
    'is-flex-widescreen': string
    'is-flex-widescreen-only': string
    'is-flex-wrap-nowrap': string
    'is-flex-wrap-wrap': string
    'is-flex-wrap-wrap-reverse': string
    'is-flexible': string
    'is-fluid': string
    'is-focused': string
    'is-four-fifths': string
    'is-four-fifths-desktop': string
    'is-four-fifths-fullhd': string
    'is-four-fifths-mobile': string
    'is-four-fifths-tablet': string
    'is-four-fifths-touch': string
    'is-four-fifths-widescreen': string
    'is-full': string
    'is-full-desktop': string
    'is-full-fullhd': string
    'is-full-mobile': string
    'is-full-tablet': string
    'is-full-touch': string
    'is-full-widescreen': string
    'is-fullhd': string
    'is-fullheight': string
    'is-fullheight-with-navbar': string
    'is-fullwidth': string
    'is-gapless': string
    'is-ghost': string
    'is-grouped': string
    'is-grouped-centered': string
    'is-grouped-multiline': string
    'is-grouped-right': string
    'is-half': string
    'is-half-desktop': string
    'is-half-fullhd': string
    'is-half-mobile': string
    'is-half-tablet': string
    'is-half-touch': string
    'is-half-widescreen': string
    'is-halfheight': string
    'is-hidden': string
    'is-hidden-desktop': string
    'is-hidden-desktop-only': string
    'is-hidden-fullhd': string
    'is-hidden-mobile': string
    'is-hidden-tablet': string
    'is-hidden-tablet-only': string
    'is-hidden-touch': string
    'is-hidden-widescreen': string
    'is-hidden-widescreen-only': string
    'is-horizontal': string
    'is-hoverable': string
    'is-hovered': string
    'is-info': string
    'is-inline': string
    'is-inline-block': string
    'is-inline-block-desktop': string
    'is-inline-block-desktop-only': string
    'is-inline-block-fullhd': string
    'is-inline-block-mobile': string
    'is-inline-block-tablet': string
    'is-inline-block-tablet-only': string
    'is-inline-block-touch': string
    'is-inline-block-widescreen': string
    'is-inline-block-widescreen-only': string
    'is-inline-desktop': string
    'is-inline-desktop-only': string
    'is-inline-flex': string
    'is-inline-flex-desktop': string
    'is-inline-flex-desktop-only': string
    'is-inline-flex-fullhd': string
    'is-inline-flex-mobile': string
    'is-inline-flex-tablet': string
    'is-inline-flex-tablet-only': string
    'is-inline-flex-touch': string
    'is-inline-flex-widescreen': string
    'is-inline-flex-widescreen-only': string
    'is-inline-fullhd': string
    'is-inline-mobile': string
    'is-inline-tablet': string
    'is-inline-tablet-only': string
    'is-inline-touch': string
    'is-inline-widescreen': string
    'is-inline-widescreen-only': string
    'is-inverted': string
    'is-invisible': string
    'is-invisible-desktop': string
    'is-invisible-desktop-only': string
    'is-invisible-fullhd': string
    'is-invisible-mobile': string
    'is-invisible-tablet': string
    'is-invisible-tablet-only': string
    'is-invisible-touch': string
    'is-invisible-widescreen': string
    'is-invisible-widescreen-only': string
    'is-italic': string
    'is-justify-content-center': string
    'is-justify-content-end': string
    'is-justify-content-flex-end': string
    'is-justify-content-flex-start': string
    'is-justify-content-left': string
    'is-justify-content-right': string
    'is-justify-content-space-around': string
    'is-justify-content-space-between': string
    'is-justify-content-space-evenly': string
    'is-justify-content-start': string
    'is-large': string
    'is-left': string
    'is-light': string
    'is-link': string
    'is-loading': string
    'is-lower-alpha': string
    'is-lower-roman': string
    'is-lowercase': string
    'is-marginless': string
    'is-max-desktop': string
    'is-max-widescreen': string
    'is-medium': string
    'is-mobile': string
    'is-multiline': string
    'is-multiple': string
    'is-narrow': string
    'is-narrow-desktop': string
    'is-narrow-fullhd': string
    'is-narrow-mobile': string
    'is-narrow-tablet': string
    'is-narrow-touch': string
    'is-narrow-widescreen': string
    'is-normal': string
    'is-offset-0': string
    'is-offset-0-desktop': string
    'is-offset-0-fullhd': string
    'is-offset-0-mobile': string
    'is-offset-0-tablet': string
    'is-offset-0-touch': string
    'is-offset-0-widescreen': string
    'is-offset-1': string
    'is-offset-1-desktop': string
    'is-offset-1-fullhd': string
    'is-offset-1-mobile': string
    'is-offset-1-tablet': string
    'is-offset-1-touch': string
    'is-offset-1-widescreen': string
    'is-offset-10': string
    'is-offset-10-desktop': string
    'is-offset-10-fullhd': string
    'is-offset-10-mobile': string
    'is-offset-10-tablet': string
    'is-offset-10-touch': string
    'is-offset-10-widescreen': string
    'is-offset-11': string
    'is-offset-11-desktop': string
    'is-offset-11-fullhd': string
    'is-offset-11-mobile': string
    'is-offset-11-tablet': string
    'is-offset-11-touch': string
    'is-offset-11-widescreen': string
    'is-offset-12': string
    'is-offset-12-desktop': string
    'is-offset-12-fullhd': string
    'is-offset-12-mobile': string
    'is-offset-12-tablet': string
    'is-offset-12-touch': string
    'is-offset-12-widescreen': string
    'is-offset-2': string
    'is-offset-2-desktop': string
    'is-offset-2-fullhd': string
    'is-offset-2-mobile': string
    'is-offset-2-tablet': string
    'is-offset-2-touch': string
    'is-offset-2-widescreen': string
    'is-offset-3': string
    'is-offset-3-desktop': string
    'is-offset-3-fullhd': string
    'is-offset-3-mobile': string
    'is-offset-3-tablet': string
    'is-offset-3-touch': string
    'is-offset-3-widescreen': string
    'is-offset-4': string
    'is-offset-4-desktop': string
    'is-offset-4-fullhd': string
    'is-offset-4-mobile': string
    'is-offset-4-tablet': string
    'is-offset-4-touch': string
    'is-offset-4-widescreen': string
    'is-offset-5': string
    'is-offset-5-desktop': string
    'is-offset-5-fullhd': string
    'is-offset-5-mobile': string
    'is-offset-5-tablet': string
    'is-offset-5-touch': string
    'is-offset-5-widescreen': string
    'is-offset-6': string
    'is-offset-6-desktop': string
    'is-offset-6-fullhd': string
    'is-offset-6-mobile': string
    'is-offset-6-tablet': string
    'is-offset-6-touch': string
    'is-offset-6-widescreen': string
    'is-offset-7': string
    'is-offset-7-desktop': string
    'is-offset-7-fullhd': string
    'is-offset-7-mobile': string
    'is-offset-7-tablet': string
    'is-offset-7-touch': string
    'is-offset-7-widescreen': string
    'is-offset-8': string
    'is-offset-8-desktop': string
    'is-offset-8-fullhd': string
    'is-offset-8-mobile': string
    'is-offset-8-tablet': string
    'is-offset-8-touch': string
    'is-offset-8-widescreen': string
    'is-offset-9': string
    'is-offset-9-desktop': string
    'is-offset-9-fullhd': string
    'is-offset-9-mobile': string
    'is-offset-9-tablet': string
    'is-offset-9-touch': string
    'is-offset-9-widescreen': string
    'is-offset-four-fifths': string
    'is-offset-four-fifths-desktop': string
    'is-offset-four-fifths-fullhd': string
    'is-offset-four-fifths-mobile': string
    'is-offset-four-fifths-tablet': string
    'is-offset-four-fifths-touch': string
    'is-offset-four-fifths-widescreen': string
    'is-offset-half': string
    'is-offset-half-desktop': string
    'is-offset-half-fullhd': string
    'is-offset-half-mobile': string
    'is-offset-half-tablet': string
    'is-offset-half-touch': string
    'is-offset-half-widescreen': string
    'is-offset-one-fifth': string
    'is-offset-one-fifth-desktop': string
    'is-offset-one-fifth-fullhd': string
    'is-offset-one-fifth-mobile': string
    'is-offset-one-fifth-tablet': string
    'is-offset-one-fifth-touch': string
    'is-offset-one-fifth-widescreen': string
    'is-offset-one-quarter': string
    'is-offset-one-quarter-desktop': string
    'is-offset-one-quarter-fullhd': string
    'is-offset-one-quarter-mobile': string
    'is-offset-one-quarter-tablet': string
    'is-offset-one-quarter-touch': string
    'is-offset-one-quarter-widescreen': string
    'is-offset-one-third': string
    'is-offset-one-third-desktop': string
    'is-offset-one-third-fullhd': string
    'is-offset-one-third-mobile': string
    'is-offset-one-third-tablet': string
    'is-offset-one-third-touch': string
    'is-offset-one-third-widescreen': string
    'is-offset-three-fifths': string
    'is-offset-three-fifths-desktop': string
    'is-offset-three-fifths-fullhd': string
    'is-offset-three-fifths-mobile': string
    'is-offset-three-fifths-tablet': string
    'is-offset-three-fifths-touch': string
    'is-offset-three-fifths-widescreen': string
    'is-offset-three-quarters': string
    'is-offset-three-quarters-desktop': string
    'is-offset-three-quarters-fullhd': string
    'is-offset-three-quarters-mobile': string
    'is-offset-three-quarters-tablet': string
    'is-offset-three-quarters-touch': string
    'is-offset-three-quarters-widescreen': string
    'is-offset-two-fifths': string
    'is-offset-two-fifths-desktop': string
    'is-offset-two-fifths-fullhd': string
    'is-offset-two-fifths-mobile': string
    'is-offset-two-fifths-tablet': string
    'is-offset-two-fifths-touch': string
    'is-offset-two-fifths-widescreen': string
    'is-offset-two-thirds': string
    'is-offset-two-thirds-desktop': string
    'is-offset-two-thirds-fullhd': string
    'is-offset-two-thirds-mobile': string
    'is-offset-two-thirds-tablet': string
    'is-offset-two-thirds-touch': string
    'is-offset-two-thirds-widescreen': string
    'is-one-fifth': string
    'is-one-fifth-desktop': string
    'is-one-fifth-fullhd': string
    'is-one-fifth-mobile': string
    'is-one-fifth-tablet': string
    'is-one-fifth-touch': string
    'is-one-fifth-widescreen': string
    'is-one-quarter': string
    'is-one-quarter-desktop': string
    'is-one-quarter-fullhd': string
    'is-one-quarter-mobile': string
    'is-one-quarter-tablet': string
    'is-one-quarter-touch': string
    'is-one-quarter-widescreen': string
    'is-one-third': string
    'is-one-third-desktop': string
    'is-one-third-fullhd': string
    'is-one-third-mobile': string
    'is-one-third-tablet': string
    'is-one-third-touch': string
    'is-one-third-widescreen': string
    'is-outlined': string
    'is-overlay': string
    'is-paddingless': string
    'is-parent': string
    'is-primary': string
    'is-pulled-left': string
    'is-pulled-right': string
    'is-radiusless': string
    'is-relative': string
    'is-responsive': string
    'is-right': string
    'is-rounded': string
    'is-selected': string
    'is-shadowless': string
    'is-size-1': string
    'is-size-1-desktop': string
    'is-size-1-fullhd': string
    'is-size-1-mobile': string
    'is-size-1-tablet': string
    'is-size-1-touch': string
    'is-size-1-widescreen': string
    'is-size-2': string
    'is-size-2-desktop': string
    'is-size-2-fullhd': string
    'is-size-2-mobile': string
    'is-size-2-tablet': string
    'is-size-2-touch': string
    'is-size-2-widescreen': string
    'is-size-3': string
    'is-size-3-desktop': string
    'is-size-3-fullhd': string
    'is-size-3-mobile': string
    'is-size-3-tablet': string
    'is-size-3-touch': string
    'is-size-3-widescreen': string
    'is-size-4': string
    'is-size-4-desktop': string
    'is-size-4-fullhd': string
    'is-size-4-mobile': string
    'is-size-4-tablet': string
    'is-size-4-touch': string
    'is-size-4-widescreen': string
    'is-size-5': string
    'is-size-5-desktop': string
    'is-size-5-fullhd': string
    'is-size-5-mobile': string
    'is-size-5-tablet': string
    'is-size-5-touch': string
    'is-size-5-widescreen': string
    'is-size-6': string
    'is-size-6-desktop': string
    'is-size-6-fullhd': string
    'is-size-6-mobile': string
    'is-size-6-tablet': string
    'is-size-6-touch': string
    'is-size-6-widescreen': string
    'is-size-7': string
    'is-size-7-desktop': string
    'is-size-7-fullhd': string
    'is-size-7-mobile': string
    'is-size-7-tablet': string
    'is-size-7-touch': string
    'is-size-7-widescreen': string
    'is-small': string
    'is-spaced': string
    'is-square': string
    'is-sr-only': string
    'is-static': string
    'is-striped': string
    'is-success': string
    'is-tab': string
    'is-text': string
    'is-three-fifths': string
    'is-three-fifths-desktop': string
    'is-three-fifths-fullhd': string
    'is-three-fifths-mobile': string
    'is-three-fifths-tablet': string
    'is-three-fifths-touch': string
    'is-three-fifths-widescreen': string
    'is-three-quarters': string
    'is-three-quarters-desktop': string
    'is-three-quarters-fullhd': string
    'is-three-quarters-mobile': string
    'is-three-quarters-tablet': string
    'is-three-quarters-touch': string
    'is-three-quarters-widescreen': string
    'is-toggle': string
    'is-toggle-rounded': string
    'is-transparent': string
    'is-two-fifths': string
    'is-two-fifths-desktop': string
    'is-two-fifths-fullhd': string
    'is-two-fifths-mobile': string
    'is-two-fifths-tablet': string
    'is-two-fifths-touch': string
    'is-two-fifths-widescreen': string
    'is-two-thirds': string
    'is-two-thirds-desktop': string
    'is-two-thirds-fullhd': string
    'is-two-thirds-mobile': string
    'is-two-thirds-tablet': string
    'is-two-thirds-touch': string
    'is-two-thirds-widescreen': string
    'is-underlined': string
    'is-unselectable': string
    'is-up': string
    'is-upper-alpha': string
    'is-upper-roman': string
    'is-uppercase': string
    'is-variable': string
    'is-vcentered': string
    'is-vertical': string
    'is-warning': string
    'is-white': string
    'is-widescreen': string
    'is-wrapped': string
    label: string
    level: string
    'level-item': string
    'level-left': string
    'level-right': string
    loader: string
    'm-0': string
    'm-1': string
    'm-2': string
    'm-3': string
    'm-4': string
    'm-5': string
    'm-6': string
    'm-auto': string
    'mb-0': string
    'mb-1': string
    'mb-2': string
    'mb-3': string
    'mb-4': string
    'mb-5': string
    'mb-6': string
    'mb-auto': string
    media: string
    'media-content': string
    'media-left': string
    'media-right': string
    menu: string
    'menu-label': string
    'menu-list': string
    message: string
    'message-body': string
    'message-header': string
    'ml-0': string
    'ml-1': string
    'ml-2': string
    'ml-3': string
    'ml-4': string
    'ml-5': string
    'ml-6': string
    'ml-auto': string
    modal: string
    'modal-background': string
    'modal-card': string
    'modal-card-body': string
    'modal-card-foot': string
    'modal-card-head': string
    'modal-card-title': string
    'modal-close': string
    'modal-content': string
    moveIndeterminate: string
    'mr-0': string
    'mr-1': string
    'mr-2': string
    'mr-3': string
    'mr-4': string
    'mr-5': string
    'mr-6': string
    'mr-auto': string
    'mt-0': string
    'mt-1': string
    'mt-2': string
    'mt-3': string
    'mt-4': string
    'mt-5': string
    'mt-6': string
    'mt-auto': string
    'mx-0': string
    'mx-1': string
    'mx-2': string
    'mx-3': string
    'mx-4': string
    'mx-5': string
    'mx-6': string
    'mx-auto': string
    'my-0': string
    'my-1': string
    'my-2': string
    'my-3': string
    'my-4': string
    'my-5': string
    'my-6': string
    'my-auto': string
    navbar: string
    'navbar-brand': string
    'navbar-burger': string
    'navbar-content': string
    'navbar-divider': string
    'navbar-dropdown': string
    'navbar-end': string
    'navbar-item': string
    'navbar-link': string
    'navbar-menu': string
    'navbar-start': string
    'navbar-tabs': string
    notification: string
    number: string
    'p-0': string
    'p-1': string
    'p-2': string
    'p-3': string
    'p-4': string
    'p-5': string
    'p-6': string
    'p-auto': string
    pagination: string
    'pagination-ellipsis': string
    'pagination-link': string
    'pagination-list': string
    'pagination-next': string
    'pagination-previous': string
    panel: string
    'panel-block': string
    'panel-heading': string
    'panel-icon': string
    'panel-list': string
    'panel-tabs': string
    'pb-0': string
    'pb-1': string
    'pb-2': string
    'pb-3': string
    'pb-4': string
    'pb-5': string
    'pb-6': string
    'pb-auto': string
    'pl-0': string
    'pl-1': string
    'pl-2': string
    'pl-3': string
    'pl-4': string
    'pl-5': string
    'pl-6': string
    'pl-auto': string
    'pr-0': string
    'pr-1': string
    'pr-2': string
    'pr-3': string
    'pr-4': string
    'pr-5': string
    'pr-6': string
    'pr-auto': string
    progress: string
    'pt-0': string
    'pt-1': string
    'pt-2': string
    'pt-3': string
    'pt-4': string
    'pt-5': string
    'pt-6': string
    'pt-auto': string
    'px-0': string
    'px-1': string
    'px-2': string
    'px-3': string
    'px-4': string
    'px-5': string
    'px-6': string
    'px-auto': string
    'py-0': string
    'py-1': string
    'py-2': string
    'py-3': string
    'py-4': string
    'py-5': string
    'py-6': string
    'py-auto': string
    radio: string
    section: string
    select: string
    spinAround: string
    subtitle: string
    table: string
    'table-container': string
    tabs: string
    tag: string
    tags: string
    textarea: string
    tile: string
    title: string
}

export type ClassNames = keyof Styles

declare const styles: Styles

export default styles
